# Generated by Django 3.2.4 on 2021-07-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_productos_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='banner',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='foto',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
