# Generated by Django 3.2.4 on 2021-07-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='banner',
            field=models.ImageField(upload_to='banners'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='foto',
            field=models.ImageField(upload_to='fotos'),
        ),
    ]
