# Generated by Django 3.2.4 on 2021-07-08 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20210707_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
        migrations.AddField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.productos'),
            preserve_default=False,
        ),
    ]
